services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb

  producer:
    build:
      context: ./Producer
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      ENABLE_SCHEDULER : "true"
    depends_on:
      - kafka

  consumer:
    build:
      context: ./Consumer
    volumes:
      - ./Consumer:/app
    env_file:
      - .env
    depends_on:
      - kafka
      - mongodb
  volumes:
    mongo_data:
      driver: local
    kafka_data:
      driver: local
    zookeeper_data:
      driver: local
    producer_data:
      driver: local
    consumer_data:
      driver: local
